package com.example.myshoppinglist.ui.theme

import androidx.compose.ui.graphics.Color

val primary = Color(0xFF3CEB54)
val primary_dark = Color(0xFF199E2B)
val secondary = Color(0xFFFFFFFF)
val secondary_dark = Color(0xFF7D7D7D)
val secondary_light = Color(0xFFC4C4C4)
var background_card = Color(0xFFEFEFEF)
val message_error = Color(0xFF9E1E40)
val text_primary = Color(0xFF000000)
val text_secondary = Color(0xFFFFFFFF)
val text_secondary_light = Color(0xBAFFFFFF)
val text_title_secondary = Color(0xFF979797)
val divider = Color(0xFFC4C4C4)
val card_blue = Color(0xFF458FB1)
val card_purple = Color(0xFF6C6BBD)
val card_pink_dark = Color(0xFFB024F0)
val card_red_light = Color(0xFFFF0000)
val card_blue_dark = Color(0xFF023F80)
val card_green_dark = Color(0xFF199E2B)
val card_green = Color(0xFF3CEB54)
val card_pink = Color(0xFFF50CDC)
val card_blue_light = Color(0xFF3A7FF5)
val card_ruby = Color(0xFFEB5B81)
val card_red_dark = Color(0xFF9E1E40)
val card_orange = Color(0xFFF38300)
val background_text_field = Color(0x2BB6FABF)
val background_text_field_dardk = Color(0xF2B6FABF)